authors = ["Rafael Fourquet <fourquet.rafael@gmail.com>"]
name = "BitFloats"
uuid = "15425d4b-8de4-5414-94ee-c672bedd8b29"
version = "0.0.2"

[deps]
BitIntegers = "c3b6d118-76ef-56ca-8cc7-ebb389d030a1"
Random      = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "≥ 1.1.0"
